create database Vaidsys_intern;
use Vaidsys_intern;
create table Website_Traffic_Analysis_1(
S_No tinyint not null,
Session_ID varchar(50) not null unique key ,
User_ID varchar(50) primary key not null unique key,
Visit_date varchar (100) not null,
Device_Type varchar(50) not null,
Browser varchar(50) not null,
Operating_System varchar(50) not null,
Traffic_Source varchar(60) not null,
Country varchar(60) not null,
City varchar(50) not null,
Landing_Page varchar(60) not null,
Exit_Page varchar(50) not null,
Bounce varchar(10) not null,
New_or_Returning varchar(50) not null,
Conversation varchar(50) not null,
Pages_Visited smallint not null,
Session_Duration smallint not null,
Page_Views tinyint not null,
Clicks smallint not null,
Revenue int not null
);
desc Website_Traffic_Analysis_1;
select*from Website_Traffic_Analysis_1;

-- 1. Find the total number of website sessions.
select count(Session_Duration) from Website_Traffic_Analysis_1;
-- 2.Find the total revenue generated by the website.
select sum(Revenue) from Website_Traffic_Analysis_1;
-- 3.Display the top 10 sessions with the highest revenue.
select Revenue from Website_Traffic_Analysis_1 order by Revenue desc limit 10;
-- 4. List all distinct traffic sources.
select Distinct(Traffic_Source) from Website_Traffic_Analysis_1 ;
-- 5.Find all users whose revenue is greater than 1000.
select User_Id from Website_Traffic_Analysis_1 where Revenue > 1000;
-- 6.Find the total revenue generated by each traffic source.
select sum(Revenue) as Total_Revenue , Traffic_Source from Website_Traffic_Analysis_1 group by Traffic_Source;
-- 7.Find the average revenue generated by each device type.
select avg(Revenue) as Averagae_Revenue,Device_type from Website_Traffic_Analysis_1 group by Device_type;
-- 8. Display traffic sources whose average revenue is greater than 500.
SELECT Traffic_source, AVG(Revenue) AS Avg_Revenue
FROM Website_Traffic_Analysis_1
GROUP BY Traffic_source
HAVING AVG(Revenue) > 500;
-- 9.Find the average session duration for each operating system.
select Operating_system, AVG(Session_Duration) as Average_duration
from website_Traffic_Analysis_1 group by Operating_system;
-- 10.Find the top 5 countries with the highest total revenue.
select Country, max(Revenue) as Highest_Revenue
from website_Traffic_Analysis_1 group by Country limit 5;
-- 11.Find users whose revenue is greater than the overall average revenue.
select User_ID, Revenue from website_Traffic_Analysis_1
where Revenue >(select AVG(Revenue) from website_Traffic_Analysis_1)limit 10;
-- 12. Find the traffic source with the highest total revenue.
select Traffic_Source, Revenue from website_Traffic_Analysis_1
where Revenue in ( select MAX(Revenue) as Highest_Total_Revenue from website_Traffic_Analysis_1);
-- 13. Find the user with the highest revenue in each country.
select User_ID,Country from website_Traffic_Analysis_1
where Revenue in ( select MAX(Revenue) as Highest_Total_Revenue from website_Traffic_Analysis_1);
-- 14.Find countries whose average revenue is greater than the overall average revenue.
select Country , AVG(Revenue) as Average_Revenue from website_Traffic_Analysis_1 
group by Country having AVG(Revenue) > (
select AVG(Revenue) from Website_Traffic_Analysis_1);
-- 15.Using a CTE, calculate the total revenue generated by each traffic source.
with Total_revenue as (
select Traffic_Source, sum(Revenue) from website_Traffic_Analysis_1 
group by Traffic_Source)
select *from Total_revenue;
-- 16.Using a CTE, find the top 3 countries with the highest revenue.
with top_3_countries as(
select Country, sum(Revenue) as Total_Revenue from website_Traffic_Analysis_1 group by Country )
select*from top_3_countries order by Total_Revenue limit 3;
-- 17.Using a CTE, find the average revenue of each device type.
with Average_Revenue as(
select Device_Type, AVG(Revenue) from website_traffic_analysis_1 group by Device_Type)
select*from Average_Revenue;
-- 18.Find the traffic source whose total revenue is greater than the average revenue of all 
select Traffic_Source,AVG(Revenue) from Website_Traffic_Analysis_1  
where Revenue > ( select avg(Revenue) from Website_Traffic_Analysis_1) group by Traffic_Source;
-- 19. Find the countries where the total revenue is greater than the total revenue of India. 
select Country, sum(Revenue) as Total_Revenue from Website_Traffic_Analysis_1 group by Country
having sum(Revenue) > (
select sum(Revenue) from website_Traffic_analysis_1 where Country = 'India');


